syntax on
set ignorecase
set hlsearch
set incsearch 
set noswapfile
set shiftwidth=4
set tabstop=4
set expandtab
set number
set relativenumber
inoremap jk <Esc>
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz

